spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/my_bank_db
    username: bank_admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: validate
  main:
    banner-mode: off
